### ISSUE TITLE
Meteor run IOS black screen ?

### ISSUE THREAD

**Issue by mmazloum** [mjwheatley/Ionic2-Meteor1.3-Starter#10]
Hi again ;-)

I've done quite a few things with your starter including DDP remote server login / accounts + reactive data. (if you want some code tell me)

My problem is that when I do Meteor run iOS, no error show up on the terminal, the app opens inside the simulator but shows a black screen, have tryed it ?

**Comment by mmazloum** [comment]
sorry was a bug on my side ;-)

**Comment by numerized** [comment]
Hello @mmazloum  I am definitely interested I'm not able to launch this starter in an actual iOS 9.3 phone, neither on a simulator. All is compiling great and works locally wonderfully but gives a grey screen after splash screen.
