### ISSUE TITLE
Reflect errors, lodash

### ISSUE THREAD

**Issue by mmazloum** [mjwheatley/Ionic2-Meteor1.3-Starter#12]
I still get those errors (may be typescript only)
client/lib/meteor-ionic-app.ts (11, 35): Property 'getMetadata' does not exist on type 'typeof Reflect'.
client/lib/meteor-ionic-app.ts (21, 17): Property 'defineMetadata' does not exist on type 'typeof Reflect'.

and I can't see how to make lodash recognized by the app
client/pages/list/list-categories.ts (40, 5): Cannot find name '_'.

If you want I figured out how to connect my project to another meteor server

**Comment by mjwheatley** [comment]
If the app still works despite those error messages, then you can get rid of the typescript error messages by declaring the variable.  

```
declare var Refelct
declare var _
```

Give that a try and let me know if it resolves this issue.

**Comment by mmazloum** [comment]
Hi works fine for Reflect thanks !

But for lodash I still get : 
client/pages/sub-list/sub-list.ts (6, 20): Cannot find module 'lodash'.

Can't figure out how to make this module recognized and this becomes a bug when building for iOS.

**Comment by mjwheatley** [comment]
I also could not get lodash to work from node_modules.
You could try a Meteor Atmosphere package.
https://atmospherejs.com/stevezhu/lodash

`meteor add stevezhu:lodash`

And then you may need
`declare var _`

**Comment by mjwheatley** [comment]
@mmazloum have you been able to try my last suggestion and did it resolve this issue for you?

**Comment by mmazloum** [comment]
no sorry I haven't tried yet, I'm giving a hand on another project, but I'll keep you posted, thanks for the support
