### ISSUE TITLE
Multiple peer dependency issues during npm install

### ISSUE THREAD

**Issue by LeonidShamis** [mjwheatley/Ionic2-Meteor1.3-Starter#13]
Hi,

Thank you for this great example.

1) I has issues during installation (multiple UNMET PEER DEPENDENCY) which I was able to fix by changing slightly the dependencies in the app\package.json file as shown below.

I have captured the "npm install" output before and after the change for your reference as well as my environment details (software versions) - all related files can be found here: [https://www.dropbox.com/sh/insj8qjaw9lrdx8/AADjBGg-G14OYRS1Ub9adLmna?dl=0](https://www.dropbox.com/sh/insj8qjaw9lrdx8/AADjBGg-G14OYRS1Ub9adLmna?dl=0)

> node -v   && npm -v   && cordova -v   && tsc --v   && typings -v   && tsd --version   && ionic -v   && ionic info
> v4.4.7
> 3.10.5
> 6.2.0
> Version 1.8.10
> 1.3.0
> 
> > tsd 0.6.5
> > 2.0.0-beta.32
> > Your system information:
> > Cordova CLI: 6.2.0
> > Gulp version:  CLI version 3.9.1
> > Gulp local:
> > Ionic Framework Version: 2.0.0-beta.10
> > Ionic CLI Version: 2.0.0-beta.32
> > Ionic App Lib Version: 2.0.0-beta.18
> > OS: Windows 7 SP1
> > Node Version: v4.4.7

  "dependencies": {
    "@angular/common": "^2.0.0-rc.3",
    "@angular/compiler": "^2.0.0-rc.3",
    "@angular/core": "^2.0.0-rc.3",
    "@angular/http": "^2.0.0-rc.3",
    "@angular/platform-browser": "^2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.3",
    "@angular/router": "^2.0.0-rc.2",
    "angular2-meteor": "0.6.0",
    "angular2-meteor-auto-bootstrap": "0.6.0",
    "angular2-meteor-polyfills": "^0.1.1",
    "es6-promise": "3.2.1",
    "es6-shim": "^0.35.0",
    "ionic-angular": "^2.0.0-beta.10",
    "ionicons": "3.0.0",
    "meteor-node-stubs": "0.2.3",
    "ng2-translate": "^2.2.2",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },

[Ionic2-Meteor1.3-Starter_install_UNMET_PEER_DEPENDENCY.txt](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter/files/385168/Ionic2-Meteor1.3-Starter_install_UNMET_PEER_DEPENDENCY.txt)
[Ionic2-Meteor1.3-Starter_install_with_modified_package.json.txt](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter/files/385169/Ionic2-Meteor1.3-Starter_install_with_modified_package.json.txt)
[package.json.txt](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter/files/385172/package.json.txt)

**Comment by mjwheatley** [comment]
I also receive the npm warnings, but they are acceptable.  The application still runs correctly for me.

Please ignore the warning messages for now and run `npm start`

npm WARN angular2-meteor@0.5.5 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN @angular/common@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN @angular/compiler@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN @angular/platform-browser@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN ng2-translate@2.1.0 requires a peer of @angular/common@2.0.0-rc.1 but none was installed.
npm WARN ng2-translate@2.1.0 requires a peer of @angular/compiler@2.0.0-rc.1 but none was installed.
npm WARN ng2-translate@2.1.0 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN ng2-translate@2.1.0 requires a peer of @angular/http@2.0.0-rc.1 but none was installed.

**Comment by LeonidShamis** [comment]
Thank you for the prompt response.
The application indeed starts and runs after the warnings/errors during "npm install".
I'm attaching full commands log - clone/install/start.
[Ionic2-Meteor1.3-Starter_notes.txt](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter/files/387542/Ionic2-Meteor1.3-Starter_notes.txt)
