### ISSUE TITLE
Application doesn't look right in Google Chrome but works fine in Firefox

### ISSUE THREAD

**Issue by LeonidShamis** [mjwheatley/Ionic2-Meteor1.3-Starter#14]
Hi,

I'm not sure if this is in any way related to the other issue ([#13](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter/issues/13)) that I've just opened, but when I first run the application after installation it doesn't look right in Google Chrome but works fine in Firefox.
Please refer to the attached screenshot or open it from the following link: [screenshot](https://www.dropbox.com/s/dnuh2u4unpgnlwx/mjwheatley_Ionic2-Meteor1.3-Starter.jpg?dl=0)
![mjwheatley_ionic2-meteor1 3-starter](https://cloud.githubusercontent.com/assets/1818114/17161870/489b0668-53f4-11e6-88be-df981fe04dd3.jpg)

**Comment by mjwheatley** [comment]
Can you revert your changes to the dependencies and see if that runs correctly in Google Chrome.  It is working correctly for me in Chrome.

**Comment by LeonidShamis** [comment]
I have cloned/installed/started the app again without applying any changes - still the same result.
Attaching the full log of commands (clone/install/start):
[Ionic2-Meteor1.3-Starter_notes.txt](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter/files/387544/Ionic2-Meteor1.3-Starter_notes.txt)

![image](https://cloud.githubusercontent.com/assets/1818114/17198764/310eabe0-54bb-11e6-85b0-883840d67db4.png)

**Comment by mjwheatley** [comment]
@LeonidShamis I am unable to replicate this issue on either Mac or Windows using Google Chrome.  
It seems like your Chrome is not interpreting the stylesheets correctly.
Are the stylesheet links appearing in the head tag with one of them disabled?
<link rel="stylesheet" type="text/css" title="ios" href="/stylesheets/ios-bundle.css">
<link rel="stylesheet" type="text/css" title="md" href="/stylesheets/md-bundle.css" disabled="">

Since it is appearing correctly in Firefox it leads me to believe that the stylesheets are being generated correctly and the fonts copied from the node_modules into your public/fonts folder.  The project seems to be built correctly.  I'm unsure why the styles are not being applied in your Chrome browser.  What version of Chrome are you running?  I have version 51.0.2704.106 m (64-bit) and 51.0.2704.103 (64-bit).  Not sure if it will matter, but doesn't hurt to check as I can't think of anything else at the moment.

**Comment by LeonidShamis** [comment]
Now that the Meteor 1.4 has been release, I have fully re-installed Meteor again (on my Windows 7) and cloned/installed/started the application again. I'm getting the same result :(

I can see links to stylesheets in head element, as expected. My Google Chrome version is 52.0.2743.82 m (64-bit).

Other Meteor and pure Ionic apps seem to be working fine in my Chrome.

I was wondering if you are aware of or have another "starter" app, maybe even simpler (i.e. without multi-language support), preferably with real (simple) collection working (displayed on a page)?

Thank you for your help.

![image](https://cloud.githubusercontent.com/assets/1818114/17239807/4921c010-55aa-11e6-913e-1f9cadd0d25e.png)

**Comment by mjwheatley** [comment]
Sorry you can't seem to get it working in your Chrome.

I attempted to update the project to Meteor 1.3.5.1 last weekend and ran into some issues.  I will try v1.4 this weekend.  

At your request I will start working on another version without internationalization and include a todo collection.

**Comment by LeonidShamis** [comment]
Hi Matthew, Thank you again for trying to troubleshoot this issue. There must be something wrong with my Google Chrome - I have tried again on another Windows 7 computer (VM) and it worked fine there, just as expected. See screenshot below. The version of Google Chrome that the application was running with was 51.0.2704.103 m and I haven't re-launched Google Chrome to apply the updated downloaded version. I'll try with updated version as well shortly and will report.

![image](https://cloud.githubusercontent.com/assets/1818114/17267899/6cf2c7fe-565a-11e6-9cb8-d2b36acda1a7.png)

**Comment by LeonidShamis** [comment]
Upgrading Google Chrome to the latest version 52.0.2743.82 m breaks it!!!
I will try searching how the new version may be affecting Ionic 2 apps...

![image](https://cloud.githubusercontent.com/assets/1818114/17267928/5ae02c40-565b-11e6-8ba1-b9c94c87f528.png)

**Comment by LeonidShamis** [comment]
I've just tried Version 54.0.2812.0 (64-bit) of the Google Chrome Canary and the application works fine with it. Will try to rollback my Google Chrome to version 51.x.x.x

**Comment by ameyapawar** [comment]
Hi,

I just cloned the current project and seems that it is not working for me in any of my installed browsers(Firefox, Chrome, Canary). I have below versions for browsers. 
1.  Chrome Canary --> Version 54.0.2817.0 canary (64-bit)
2.  Firefox --> Version 48.0
3.  Chrome --> Version 52.0.2743.116 m (64-bit)

See attached snapshots for errors.

![browser issue](https://cloud.githubusercontent.com/assets/18413995/17408078/6b792c3e-5a87-11e6-94de-8e9def8c26f2.png)

Also, i tried to re-install all this browsers to check if it works, but still the same issue.
The earlier version of the same app works fine with me in all current browsers. 
Can you please suggest/comment on this?

Thanks!

**Comment by mjwheatley** [comment]
@ameyapawar it sounds like your sass did not compile.  Please check your ios-bundle.css and md-bundle.css files in the app/public/stylesheets/ directory.  If they are empty then there was a error during the build:ios-css and build:md-css scripts executed by `npm start`.  If you have changed your node version recently you may need to run `npm rebuild node-sass`.  Please look at the stack trace after running `npm start` and report if there are any errors during the css build scripts.

**Comment by ameyapawar** [comment]
Hi Matthew,

Indeed that worked for me. Thanks :)
I am now trying to have this built as a Android App.
I am trying to built it using meteor command set. But, had to do some troubleshoot. 

Can you please comment on what set of commands you might use to generate apk file for this app?
I already tried to change the Package.Json file to have "meteor run android-device". 
Thanks!

**Comment by mjwheatley** [comment]
For deployment:

```
npm run build
meteor build --directory ../build/ --mobile-settings ../config/development/settings.json --server https://www.yourdomain.com --architecture os.linux.x86_64
```

Open Android Studio, import the project from Ionic2-Meteor-Starter/build/android/project, then generate and sign the apk as a normal.
