### ISSUE TITLE
Add documentation for adding cordova/ionic native plugins

### ISSUE THREAD

**Issue by idesignpixels** [mjwheatley/Ionic2-Meteor1.3-Starter#16]
How do you add plugins in this setup?
I know ionic native makes things easier but doesn't seem to be implemented here, do you use ionic or meteor like this `meteor add cordova:cordova-plugin-geolocation@2.0.0`

**Comment by mjwheatley** [comment]
This is a Meteor application so you are correct.
`meteor add cordova:name-of-cordova-plugin@version`
