### ISSUE TITLE
Stuck on SplashScreen for iOS

### ISSUE THREAD

**Issue by ddett** [mjwheatley/Ionic2-Meteor1.3-Starter#2]
I installed the application as described. I was able to run it successfully in the browser. When trying "meteor run ios" (for simulator) or "meteor run ios-device" (iPhone 6s iOS 9.2) I'm stuck with the splash screen showing the meteor logo.

**Comment by mjwheatley** [comment]
Fixed issue with latest commit.  Please clone the repo again and test to confirm.  Thanks.
