### ISSUE TITLE
platform.ready() is never called when using @angular.rc1

### ISSUE THREAD

**Issue by chriswep** [mjwheatley/Ionic2-Meteor1.3-Starter#4]
i updated angular (and accordingly most of the other packages, including ionic) to the current version (rc1). so far no problem, no error messages, but the platform.ready() isn't called anymore. any idea?

**Comment by mjwheatley** [comment]
Not really sure.
Which platform, Android, iOS, or both?
I found [this post](https://github.com/driftyco/ionic/issues/6186) about the issue, but it looks like it should be resolved.

As a potential workaround, trying creating a deviceready.js file in the client/lib/ folder with the following code.

```
Meteor.startup(function () {
    if (Meteor.isCordova) {
        document.addEventListener('deviceready', onDeviceReady, false);
    }
});

function onDeviceReady() {
    Session.set("deviceReady", true);
    // Listen for application resumed event
    document.addEventListener('resume', onResume, false);

    // Set StatusBar Style
    StatusBar.styleLightContent();

};

function onResume() {
};
```

Then use an autorun in ngOnInit() of app.ts to monitor the reactive Session variable for "deviceReady."

```
this.autorun(() => {
    if (Session.get("deviceReady")) {
        // Put your "deviceready" dependent initialization code here
    }
});
```

**Comment by chriswep** [comment]
i could fix it now, though the issue you posted was not the problem. Your MeteorIonicApp class has to be updated to the current version of ionic.
I changed my setup quite a bit from the one in this repo, but if you are interested i can fork your repo and create a pull request with the updated code (and package versions).

**Comment by mjwheatley** [comment]
Yes, that would be great.
