### ISSUE TITLE
npm start errors logs

### ISSUE THREAD

**Issue by mmazloum** [mjwheatley/Ionic2-Meteor1.3-Starter#5]
Hi,

first thanks thanks for the great work I saw you helped a lot arround, I'm trying to find a working version of this such a starter with angular rc which seems more easy to play with.

However I tryed this starter and unfortunately it threw errors that I couldn't manage at npm start : 

{ Error: ENOENT: no such file or directory, open 'public/stylesheets/ios-bundle.css'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'public/stylesheets/ios-bundle.css' }

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "build:ios-css"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! Meteor-v1.3-Ionic2-Starter@0.0.1 build:ios-css: `node-sass --include-path node_modules/ionic-angular --include-path node_modules/ionicons/dist/scss client/theme/app.ios.scss | postcss --local-plugins --use autoprefixer --output public/stylesheets/ios-bundle.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Meteor-v1.3-Ionic2-Starter@0.0.1 build:ios-css script 'node-sass --include-path node_modules/ionic-angular --include-path node_modules/ionicons/dist/scss client/theme/app.ios.scss | postcss --local-plugins --use autoprefixer --output public/stylesheets/ios-bundle.css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Meteor-v1.3-Ionic2-Starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-sass --include-path node_modules/ionic-angular --include-path node_modules/ionicons/dist/scss client/theme/app.ios.scss | postcss --local-plugins --use autoprefixer --output public/stylesheets/ios-bundle.css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Meteor-v1.3-Ionic2-Starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Meteor-v1.3-Ionic2-Starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marwanmazloum/Desktop/Developpement/sandbox/Ionic2-Meteor1.3-Starter/app/npm-debug.log
ERROR: build:ios-css: None-Zero Exit(1);

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! Meteor-v1.3-Ionic2-Starter@0.0.1 start: `npm-run-all build:* --parallel watch:* meteor`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Meteor-v1.3-Ionic2-Starter@0.0.1 start script 'npm-run-all build:\* --parallel watch:\* meteor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Meteor-v1.3-Ionic2-Starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all build:\* --parallel watch:\* meteor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Meteor-v1.3-Ionic2-Starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Meteor-v1.3-Ionic2-Starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marwanmazloum/Desktop/Developpement/sandbox/Ionic2-Meteor1.3-Starter/app/npm-debug.log
MacBook-Air-de-Marwan:app marwanmazloum$

**Comment by mjwheatley** [comment]
Did you create the public/stylesheets/ directory? If so, check the directory permissions.  You may need to change the owner using the `chown` command.  Just my first guess.  Check it out and let me know.

**Comment by mmazloum** [comment]
sorry I misspelled stylesheets... everything works fine, are the angular2-meteor guys planning to handle this on angular2.rc ?

**Comment by mjwheatley** [comment]
I have updated this project to use angular2.rc.1 along with ionic-angular@2.0.0-beta.7
