### ISSUE TITLE
Meteor.user() is not a function

### ISSUE THREAD

**Issue by mjwheatley** [mjwheatley/Ionic2-Meteor1.3-Starter#7]
After updating this project to use angular@2.0.0-rc.1 and ionic-angular@2.0.0-beta.7 the Meteor.user() method is no longer recognized as a valid function.

**Comment by mmazloum** [comment]
Awesome ! Thanks I'll try it ASAP. I didn't see Meteor-accounts in your packages ? maybe that's why your Meteor.user() is not found, I'll try to take a closer look at it (with my beginner skills) later.

**Comment by mjwheatley** [comment]
Yep, that was totally it.  I've grown so accustomed to using that feature I forgot that it was part of a separate package and not part of the core bundle.  Nice catch for a so-called "beginner."
