### ISSUE TITLE
Little suggestion about the viewport

### ISSUE THREAD

**Issue by mmazloum** [mjwheatley/Ionic2-Meteor1.3-Starter#8]
If you add : 
`<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">` in index.html

The app will look more like a mobile app, for now the content is a bit small when simulating a mobile viewport.

**Comment by mjwheatley** [comment]
OMG Thanks! That has been driving me crazy.  I'm working on another app that didn't have that issue and I could not pinpoint why that app was different than this one when using the the device view of the Chrome dev console.  Turns out that app had that same meta tag you mentioned.  Thanks for pointing out that line of code.  I added that line of code and pushed a new commit.

**Comment by mmazloum** [comment]
nothing compared to how your repo is usefull to me ;-) by the way I have a
question about using OrionJS (Meteor CMS Package) as an app Backoffice, I
wonder how to route the Admin part which is a web app and having the native
app on the other side ? should I deploy a separate server and use DDP or is
there a routing trick ?

2016-06-07 17:25 GMT+02:00 Matthew Wheatley notifications@github.com:

**Comment by mjwheatley** [comment]
I'm still trying to figure out some routing issues myself.  I am used to using the iron:router package for Meteor so the Angular2 router is new to me.  I am in need of creating some server only routes for use as a RESTful API.  If you are wanting to use a separate web app as an Admin console you have a few options.  You can create an admin restricted server API, you can connect that app via DDP as you mentioned, or you could connect the CMS to the same MongoDB.  Unfortunately I do not have any experience doing any of those things yet so I am unable to provide assistance.  I will be trying to figure out some of those things myself and would be happy to share any progress I am able to make.  I'd be happy to know if you figure anything out as well.  Best of luck.

**Comment by mmazloum** [comment]
Ok then I'll keep you updated.

Try flow router, it's much more clean, easier and cleaner to use than iron
router. I can send peaces of code if needed. or we can schedule a skype
session.

I have 2 to options to explore :
- https://forums.meteor.com/t/different-interfaces-based-on-devices/264/2
  (which
  seems most likely to do the job)
  or
- https://github.com/barbatus/angular2-meteor-universal (not ready yet, but
  planned to merge with the official socially tutorial with in depth routing
  code examples based on flow-router.

we could skype here if you wish : marwan.mazloum

best of luck too

2016-06-08 15:58 GMT+02:00 Matthew Wheatley notifications@github.com:
